// Code generated by mockery v1.0.0. DO NOT EDIT.

package servicemocks

import localization "github.com/darianfd99/geo/pkg"
import mock "github.com/stretchr/testify/mock"

// Localization is an autogenerated mock type for the Localization type
type Localization struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *Localization) GetAll() ([]localization.Localization, error) {
	ret := _m.Called()

	var r0 []localization.Localization
	if rf, ok := ret.Get(0).(func() []localization.Localization); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]localization.Localization)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Post provides a mock function with given fields: id, lat, long
func (_m *Localization) Post(id string, lat float64, long float64) (localization.GroupAvaerageLocation, error) {
	ret := _m.Called(id, lat, long)

	var r0 localization.GroupAvaerageLocation
	if rf, ok := ret.Get(0).(func(string, float64, float64) localization.GroupAvaerageLocation); ok {
		r0 = rf(id, lat, long)
	} else {
		r0 = ret.Get(0).(localization.GroupAvaerageLocation)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, float64, float64) error); ok {
		r1 = rf(id, lat, long)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
